export const foods = [
        {
            id:1,
            category: "coffee",
            name:'American Coffee',
            description:'Strong j-packed shot coffee.',
            price: 10.15,
            image_url: require('../assets/coffee.jpg'),
            order: 15,
        },
        {
            id:2,
            category: "coffee",
            name:'Caffè mocha',
            description:'Chocolate-flavoured warm.',
            price: 15.07,
            image_url: require('../assets/coffee02.jpg'),
            order: 0,
        },
        {
            id:3,
            category: "coffee",
            name:'Cappuccino Coffee',
            description:'Traditionally steamed milk foam.',
            price: 18.20,
            image_url: require('../assets/coffee03.jpg'),
            order: 0,
        },
        {
            id:4,
            category: "coffee",
            name:'Cold Coffee',
            description:'Strong brazilian shot coffee.',
            price: 15.00,
            image_url: require('../assets/coffee04.jpg'),
            order: 0,
        },
        {
            id:5,
            category: "snack",
            name:'Indian Ariselu',
            description:'Flour, soaked rice, and molten jaggery, etc.',
            price: 21.01,
            image_url: require('../assets/snack.jpg'),
            order: 0,
        },
        {
            id:6,
            category: "snack",
            name:'Banana Fritter',
            description:'Deep-frying battered banana or plantain.',
            price: 11.15,
            image_url: require('../assets/snack02.jpg'),
            order: 0,
        },
        {
            id:7,
            category: "snack",
            name:'Badusha Food',
            description:'South Indian food similar to glazed donut.',
            price: 10.75,
            image_url: require('../assets/snack03.jpg'),
            order: 0,
        },
        {
            id:8,
            category: "snack",
            name:'Gulab Jamun',
            description:'Dessert made with milk, cheese solids.',
            price: 12.75,
            image_url: require('../assets/snack04.jpg'),
            order: 20,
        },
        {
            id:9,
            category: "beverage",
            name:'Watermelon Juice',
            description:'A delicious and thirst quenching.',
            price: 25.15,
            image_url: require('../assets/beverage.jpg'),
            order: 0,
        },
        {
            id:10,
            category: "beverage",
            name:'Healthy Squash',
            description:'Refreshing and rejuvenating.',
            price: 17.45,
            image_url: require('../assets/beverage02.jpg'),
            order: 0,
        },
        {
            id:11,
            category: "beverage",
            name:'Boba Thai Tea',
            description:'Wide straw juicy boba and tea.',
            price: 20.99,
            image_url: require('../assets/beverage03.jpg'),
            order: 0,
        },
        {
            id:12,
            category: "beverage",
            name:'Milky Oreo Squash',
            description:'Juicy, milky, and sweetie squash.',
            price: 21.99,
            image_url: require('../assets/beverage04.jpg'),
            order: 30,
        },
        {
            id:13,
            category: "italian",
            name:'Tomato Pizza',
            description:'Sweet and super tasty pizza.',
            price: 21.15,
            image_url: require('../assets/pizza.jpg'),
            order: 0,
        },
        {
            id:14,
            category: "italian",
            name:'Mexican Taco',
            description:'Made with spit-grilled meat.',
            price: 24.50,
            image_url: require('../assets/pizza02.jpg'),
            order: 0,
        },
        {
            id:15,
            category: "italian",
            name:'Italian Pasta',
            description:'Strong, squisy beef and noodle.',
            price: 16.20,
            image_url: require('../assets/pizza03.jpg'),
            order: 0,
        },
        {
            id:16,
            category: "italian",
            name:'Luxury Indomie',
            description:'A luxury hicky-picky flavours.',
            price: 22.45,
            image_url: require('../assets/pizza04.jpg'),
            order: 22,
        },
        {
            id:17,
            category: "burger",
            name:'Burger Deluxe',
            description:'Our delicious pure beef patty.',
            price: 18.50,
            image_url: require('../assets/burger.jpg'),
            order: 0,
        },
        {
            id:18,
            category: "burger",
            name:'Bøfsandwich',
            description:'Cooked ground beef patty, oil.',
            price: 16.99,
            image_url: require('../assets/burger02.jpg'),
            order: 0,
        },
        {
            id:19,
            category: "burger",
            name:'Buffalo burger',
            description:'Less cholesterol, less fat,calories.',
            price: 12.75,
            image_url: require('../assets/burger03.jpg'),
            order: 0,
        },
        {
            id:20,
            category: "burger",
            name:'50/50 burger',
            description:'Half ground bacon, half ground beef.',
            price: 19.99,
            image_url: require('../assets/burger04.jpg'),
            order: 50,
        }
]